config/routes.rb
Photogur::Application.routes.draw do
  root :to => 'pictures#index'           # the '/' => makes it the home index, same thing as root

  resources :pictures

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
# include Magic!! In the pictures database that was created there is title, artist
# and url. Rails knows that when Picture class is callsed it is looking 
# for the Pictures table (which is in the CreatePictures Class)

	# Allow mass-assignment for the attributes titles and artist
	attr_accessible :title, :artist, :url, :copyrighted
	# Don't confuse this with attr_accessor!!!

	validates :title, :presence => true
	validates :artist, :presence => true
	validates :url, {
		:format => {
			:with => /^https?:/, :message => "Please enter a valid email address"
		}
	}

	scope :alphabetical, order("title ASC")
	scope :free, where(:copyrighted => false)

end


# purpose of having attr_accessible is primarily for security. 
# it controls things like user_accessible which is a mass change function that 
# permits user to make changes to all data. 
# by excluding the :admin from attr_accessible, you are preventing them from
# adding themselves as an admin and makign mass [global] changes

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	#before_filter :load_pictures #this will occcur before going into teach of the methods

	def index
		if params[:free] == "yes"
			@pictures = Picture.free.alphabetical.all
		else
			@pictures = Picture.alphabetical.all     	# this is what
		end
	end

	def show
		@picture = Picture.find params[:id]
	end

	def new
		@picture = Picture.new
	end

	def create
		@picture = Picture.new(params[:picture])	# instance of picture created in controller new, the parameters set in new.html.erb
		if @picture.save
			redirect_to pictures_path 			# pictures_path, this tells you to access the /pictures. alternative is :action => "index"

		else  #there was an error on the form
			flash.now[:error] = "Some fields are blank"
			render :new	
		end
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])
		
		if @picture.update_attributes(params[:picture])
			redirect_to picture_path@picture.id 			# "/pictures/#{@picture.id}"
		else
			#something
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur, by Christine and Tom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Inder' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class ="nav">
			<ul>
				<li><%= link_to "Home", pictures_path %></li>
				<li><%= link_to "New Picture", new_picture_path %></li>
			</ul>
		</div>		
<%= yield %>    <!-- the yield tag calls all the html.erb views -->
	
	</div>
</body>
</html>

app/views/pictures/_form.html.erb
 <%= form_for @picture do |f| %>
	<p>
		<lable>Artist</lable><br>
		<!-- <input type = "text" name = "artist"/> --> 
		<%= f.text_field "artist" %>
	</p>

	<p>
		<lable>Title</lable><br>
		<!-- <input type = "text" name = "title"/> -->
		<%= f.text_field "title" %>
		<%= @picture.errors.messages[:title].join("") %>
	</p>

	<p>
		<lable>URL</lable><br>
		<!-- <input type = "text" name = "url"/> -->
		<%= f.text_field "url" %>
		<%= @picture.errors.messages[:url].join("") %>
	</p>

	<p>
		<%= f.check_box "copyrighted" %>
		<%= f.label "copyrighted", "Photo is copyrighted" %>
	</p>

	<p>
	<!-- 	<input type = "submit"/> -->
		<%= f.submit "Save" %>
	</p>

<!-- </form> -->
<% end%>

app/views/pictures/edit.html.erb
<h1> Edit Picture </h1>

<%= render :partial => "form" %>	

app/views/pictures/index.html.erb
<% link_to "Free pictures only", pictures_path(:free => "yes") %>


<h1>Photogur</h1>

<!-- <a href="<%new_picture_path %>">New Picture</a> -->


<%- @pictures.each do |picture| %>
	<p class = "title"><%=picture.title%> </p>
	<p class = "artists"> <%=picture.artist%> </p>
	
	<!-- <a href ="<%=picture_path(picture.id)%>"><img src="<%=picture.url%>"></a> -->
	<!-- <a href = "<%= edit_picture_path(picture) %>"> Edit </a></br> -->
	<%= link_to picture_path(picture) do %>
	<%= image_tag picture.url %>
	<% end %>
<% end %> 


<!-- calling Pictures.all 
the .all function is what makes the pictures return to us as an array. It collects 
all the information and returns it to us in array format
 -->

app/views/pictures/new.html.erb
<h1> Add a picture </h1>


<div class = "errors">
	<%= flash[:error] %>
</div>

<%= render :partial => "form" %>		<!-- Looks for _form.html.erb -->

app/views/pictures/show.html.erb
<p><%= params %></p>     

<h1><%= @picture[:title] %></h1>
<p><%= @picture[:artist]%></p>
<img src="<%= @picture[:url] %>">
<%= button_to "Delete", @picture, :method => :delete, :confirm => "Are you sure you want to delete?" %>
<%= button_to "Edit", edit_picture_path(@picture), :method => :get %>

<% if @picture.copyrighted %>
	<p>This picture is copyrighted.</p>

<% end %>